apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-conf
  namespace: monitoring-tick
data:
  elasticsearch.yml: |
    network.host: 0.0.0.0
    xpack.notification.email.account:
      account:
        smtp:
          host: 192.9.201.3
          port: 25