---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: monitoring-tick
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: repodev.cib.ru:8082/kibana:7.6.0
        env:
          - name: 'ELASTICSEARCH_URL'
            value: 'http://elasticsearch:9200/'

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: monitoring-tick
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      nodePort: 32011


