---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: monitoring-tick
  name: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: repodev.cib.ru:8082/logstash:7.6.0
        volumeMounts:
#          - name: logstash-conf
#            mountPath: /usr/share/logstash/config
          - name: 'logstash-pipeline'
            mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: 'logstash-conf'
          hostPath:
            path: /opt/tick/logstash/conf
        - name: 'logstash-pipeline'
          hostPath:
            path: /opt/tick/logstash/pipeline
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: logstash
#  namespace: monitoring-tick
#spec:
#  selector:
#    app: logstash
#  ports:
#    - name: port1
#      port: 9200
#      targetPort: 9200
#    - name: port2
#      port: 9300
#      targetPort: 9300
#---
apiVersion: v1
kind: Service
metadata:
  name: logstash-nodeport
  namespace: monitoring-tick
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
    - port: 5044
      protocol: UDP
      nodePort: 30044

#
#
#
